<?php
include 'header.php'; 
?>
	<h1>I- Causes et effets du technostress</h1>
	<!-- PARTIE A -->
	<h2><a name="a"></a>A. La genèse du technostress</h2>
	<p>Si l’on s’interroge sur la genèse du technostress, on ne peut pas faire l’impasse sur l’essor des NTIC que nous connaissons depuis maintenant une dizaine d’années. En l’espace de peu de temps, ce sont nos manières de communiquer qui ont été complètement « chamboulées » par les nouvelles technologies de l’information et de la communication. L’arrivée de l’Internet, du haut débit accessible à tous, les téléphones portables, les forfaits SMS illimités puis récemment les smartphones qui permettent d’être connecté à Internet en permanence font partie de cet essor des NTIC.</p>

	<p>Tous ces nouveaux moyens de communication ou leurs évolutions ont permis de pouvoir communiquer avec plus de personnes, sans souci de distance, toujours plus rapidement et via toujours plus de supports (appels téléphoniques, SMS, e-mails, messagerie instantanée, réseaux sociaux, visioconférence…). Les NTIC nous ont permis d’être plus reliés les uns aux autres, au sens technologique du terme, avec plus de facilité et plus de vitesse. En plus de nous permettre de communiquer différemment, les NTIC nous permettent de nous documenter plus rapidement, de n’importe où (sous réserve d’avoir accès à Internet) et surtout avec une multitude d’informations.</p>

	<p>Cette masse toujours plus grande d’informations nous permet de satisfaire la large majorité de nos recherches mais nous contraint également à effectuer un travail de tri conséquent. L’information étant tellement vaste, on parle de surinformation ou même d’infobésité. Chacune et chacun d’entre nous a aujourd’hui accès par une diversité de canaux, de la radio à Internet, du téléphone portable à la télévision, à une multitude d’informations instantanées et en continu. Ce roulis ininterrompu donne le sentiment d’être toujours informé. Parfois, il assiège plus les personnes qu’il ne les libère. Cette surinformation chasse l’information et sa hiérarchisation.</p>

	<p>L’essor des NTIC a apporté son lot de mutations au sein du monde professionnel. Aujourd’hui, la plupart des grandes entreprises offrent à leurs salariés une boite mail professionnelle. Ainsi, les informations liées à l’entreprise transitent majoritairement par les e-mails : les réunions, les informations, les demandes de rapports, les demandes de rendez-vous entre collègues… On note souvent la présence de listes de diffusions au sein de chaque entreprise qui permettent à l’ensemble des utilisateurs inscrits de recevoir les e-mails adressés à la liste de diffusion. Les listes de diffusions regroupent souvent l’ensemble des personnes d’un même service au sein d’une entreprise, et ainsi, chaque service possède sa propre liste de diffusion.</p>

	<p>L’e-mail en entreprise a permis de réduire la barrière de communication avec la hiérarchie ou les collègues des différents services de l’entreprise mais l’existence de listes de diffusions, la facilité et la rapidité de rédaction d’un e-mail poussent chaque employé à participer à la saturation des boites mails de l’ensemble de l’entreprise.</p> 

	<p>L’essor des NTIC a donc poussé les entreprises à changer leurs méthodes de management en intégrant ces nouveaux outils de communication et d’information à leur organisation.</p> 

	<p>Comme nous l’avons vu précédemment, les NTIC ont permis de faciliter la communication au sein de l’entreprise, de nous informer rapidement et de garder le contact avec notre entourage mais les inconvénients générés par les NTIC sont nombreux et sont responsables du phénomène de technostress dont sont victimes certaines personnes.</p>
	<!-- PARTIE B -->
	<h2><a name="b"></a>B. La pression permanente des entreprises</h2>
	<p>Les NTIC sont parfois utilisées en entreprise comme un moyen de surveillance de l’employé. De nombreuses activités sont maintenant contrôlées par des réseaux d’ordinateurs telles que : frappe dactylographique par minute, vitesse de réponse téléphonique lors des demandes d’informations, fréquence des pauses, longueur des temps de repos etc. Ces activités contrôlées électroniquement concernent des millions de travailleurs des compagnies aériennes, des administrations publiques, des compagnies d’assurance, des compagnies de téléphone et de communication...</p> 

	<p>Les réseaux d’ordinateurs sont souvent programmés pour obtenir la réalisation d’objectifs fixés qui contraignent les employés à travailler de plus en plus vite pour les réaliser. Grâce aux réseaux électroniques, il est possible de suivre avec précision l’avancement des tâches. Or, les ordinateurs mesurent plus la quantité que la qualité, et ce sont ainsi les opérateurs les plus rapides qui sont récompensés, non ceux qui effectuent un travail de qualité !</p>

	<p>Les statistiques qui sont tirées de ces résultats ont pour but de mettre en évidence la présence de temps morts et d’établir un classement entre les différents salariés. La recherche de performance est partout et est régie par une surveillance technologique toujours plus accrue.</p>

	<p>À cette surveillance technologique déjà génératrice de stress, s’ajoutent les nouvelles méthodes de communication utilisées en entreprise. La messagerie instantanée, les réunions en visioconférence, les intranets, les blogs, les forums et bien sûr, les e-mails. Si les salariés ont longtemps manqué d'information, ils en sont aujourd'hui submergés. « Un cadre reçoit en moyenne 150 messages par jour. Il est donc interrompu toutes les quatre minutes » note Yves Lasfargue, sociologue. Si certains ont compris que 60 % des e-mails relevaient du spam, d'autres vivent dans la crainte de  rater une information importante et consultent frénétiquement leur boite de réception durant toute la journée. Le cadre doit faire le tri parmi cette masse d'informations et accepter d'en abandonner sans culpabiliser.</p>

	<p>L’e-mail, initialement érigé comme sainte solution pour rétablir la communication en entreprise est aujourd’hui l’un des plus gros problèmes. Les employés sont submergés d’e-mails à longueur de journée et sont constamment interrompus dans leurs tâches par des alertes de réception de nouveaux messages sur leurs ordinateurs ou leurs smartphones qui les suivent en dehors du lieu de travail. Cette interruption à répétition est contre-productive et  la masse importante d’informations oblige chaque employé à faire le tri, pour finalement s’apercevoir que 80 % des informations qu’il a reçues ne le concernaient pas directement ou ne lui étaient pas utiles.</p> 

	<p>Les employés sont souvent poussés par leur entreprise à transférer ou à mettre en copie leurs supérieurs ou leurs collègues afin de les tenir informés de chaque communication, chaque information qui transite. Cette pratique est dans la continuité de la surveillance technologique décrite au début de cette partie : l’entreprise voulant pouvoir tracer le travail de chacun, chaque employé doit pouvoir justifier (ou se dédouaner) d’avoir pris une décision. Là encore, cette pratique contribue au flot important d’e-mails qui viennent submerger les autres employés.</p>

	<p>L’e-mail s’est tellement ancré dans l’organisation de l’entreprise que certains salariés ne sont plus capables de décrocher leur téléphone ou de grimper quelques étages pour établir une communication directe avec leur interlocuteur, ce qui éviterait un échange d’e-mails, serait un gain de temps conséquent et permettrait une communication plus efficace et plus humaine.</p>

	<p>La surveillance technologique, la forte utilisation des NTIC tant dans notre vie professionnelle que dans notre vie privée conduit certaines personnes à souffrir de technostress. Ne pouvant plus répondre en temps et en heure aux messages, ressentant le besoin compulsif de vérifier leurs boites e-mails, étant sans cesse perturbées par des alertes et des messages de notification, ces personnes se sentent emprisonnées par la technologie. Elles ne parviennent plus à se déconnecter sous la pression permanente de leur entreprise.</p>

	<p>De nombreuses entreprises sont encore dans le déni du problème. Et si les gens souffrent, elles ne se battent pas pour autant, parce que la communication est censée être bonne pour l’employé. L’entreprise n’a pas d’états d’âme et ne répond qu’à une logique de productivité. L’e-mail a été la source d’une forte accélération du rythme imposé par le travail. Cette charge est aujourd’hui alourdie par les smartphones qui créent une obligation de réactivité. La logique de compétitivité implique de répondre aux sollicitations en temps réel, de n’importe où, avec n’importe quel appareil et à n’importe quelle heure. Ceci nous amène à nous demander si les NTIC ne favorisent pas une rupture de la barrière entre la vie privée et la vie professionnelle.</p>
	<!-- PARTIE C -->
	<h2><a name="c"></a>C. La rupture de la barrière vie professionnelle / vie privée</h2>
	<p>Qui ne s'est pas entendu dire qu'il préférait travailler chez lui, au calme, le week-end ou en RTT ? Cette interpénétration entre la vie privée et la vie professionnelle est entretenue par les entreprises, qui fournissent gratuitement le matériel et l'ADSL. Sans pour autant instituer un cadre légal à cette forme de télétravail.</p> 

	<p>En effet, de nombreux cadres se voient maintenant offrir un smartphone par leur entreprise. Mais cette précieuse machine est en réalité un cadeau empoisonné : le caractère distrayant et novateur du smartphone ne  prive pas pour autant le cadre d’être relié en permanence à son travail. Connecté en continu à l’internet, le smartphone bipe à longueur de journées et les notifications pleuvent : nouveaux e-mails, appels téléphoniques, SMS, réseaux sociaux, rappels de calendrier… Le salarié est au bureau sans y être. À toute heure du jour, voire de la nuit, il relève son courrier dans le train, à l'aéroport, dans sa chambre d'hôtel. Les fournisseurs se servent de ce comportement comme argument de vente. Le constructeur de terminal BlackBerry évoque, en guise de retour sur investissement, une réduction des temps morts de 47 minutes par jour. A qui profite-t-elle ?</p>
	
	<p>Il devient alors impossible pour le salarié de se déconnecter : les NTIC le rappellent au travail n’importe quand et n’importe où.</p>

	<p>Certains s'enivrent de cette puissance amenée par la technologie. Du bout des doigts, ils peuvent toucher le monde entier ! Nicole Aubert, sociologue et psychologue, les appelle les shootés à l'urgence. « L'urgence devient une amphétamine, qui permet de vivre plus fort, plus vite, plus intensément ». Le technostress se mêle alors au plaisir, et peut déboucher sur un comportement de type « accro » : la cyberdépendance.</p>

	<p>D’après une étude menée par AOL en 2008 auprès d’un échantillon de 4 000 utilisateurs américains de courriers électroniques, 46 % des personnes étaient « prisonnières » de l’e-mail. Près de 60 % d’entre eux relevaient leurs messages dans la salle de bain, 15 % à l’église (alors que le pays est très catholique) et 11 % cachaient le fait qu’ils vérifiaient leurs messages à partir de l’appareil de leur conjoint ou d’un autre membre de la famille. Plus inquiétant encore, une étude menée par TeleNav en 2011 auprès de 600 utilisateurs américains de smartphones montre que 33 % d’entre eux sont prêts à abandonner les relations sexuelles plutôt que leur smartphone pendant une semaine.</p>

	<p>Beaucoup de cadres et de managers n’ont pas le temps de gérer leur courrier (certains en reçoivent plus d’une centaine par jour) et doivent le traiter à la maison, parfois jusqu’à des heures tardives. « La possibilité de traiter les e-mails à distance a modifié l’organisation hebdomadaire du travail, note un cadre d’un fournisseur d’accès à Internet. Les réunions du lundi matin se déroulent désormais dès 9 h 30 car les managers supposent que les salariés se sont connectés durant le week-end. Du coup, plus besoin de leur laisser le temps de préparer la réunion en arrivant ! ». Mais l’e-mail ne suit pas seulement le salarié rentrant chez lui le soir, il l’accompagne également lors de ses arrêts maladies, de ses déplacements, de ses vacances… L’accès à une connexion internet est aujourd’hui un critère déterminant lors du choix de la destination des vacances pour de nombreux salariés.</p>
	
	<center><img src="//www.technostress.fr/images/cadre_relax.jpg" width="500px" class="photo" alt="Cadre en vacances" /></center>
	<center><span class="italic">Un cadre travaillant sur son ordinateur en vacances</span></center>
	<br />
	<p>Le flot continu de requêtes et le fait de devoir répliquer instantanément posent problème. Cette sollicitation agit comme un poison lent, insidieux. Il devient alors difficile de ne pas se laisser déborder dans un système de hiérarchie contrainte où la connexion peut se transformer en aliénation. On assiste à une fusion des mondes privé et professionnel. Certains ne trouvent plus leur place et se sentent mal partout.</p>

	<p>La multiplication des machines électroniques (ordinateurs, smartphones, tablettes, beepers) facilite les contacts entre personnes à tout moment, avec, comme corollaire, la disparition progressive de contacts personnels. Cet environnement électronique a des effets sur le psychisme individuel dans la mesure où ces personnes exigent, une fois rentrées chez elles, la même vitesse de réponse (que leurs ordinateurs) des membres de leurs familles. Habituées à un temps de réponse éclair de la part de leurs machines tout en étant habituées au multitâche, les personnes atteintes de technostress ont du mal à accepter la lenteur relative de leur entourage et en deviennent irritables.</p> 

	<p>Certains s’enferment dans un monde où la technologie règne en maitre tandis que d’autres développent des symptômes phobiques vis-à-vis des machines électroniques. Le sentiment d’isolement social devient de plus en plus fréquent alors que les moyens de communication mis à disposition sont plus importants.</p>
	
	<!-- PARTIE D -->
	<h2><a name="d"></a>D. Les effets du technostress et leurs dangers</h2>
	<p>Maintenant que nous avons vu les différentes causes de l’apparition du technostress, attachons-nous à leurs effets.</p>

	<p>Tout d’abord, il apparaît que notre cerveau n’est pas adapté au multitâche et aux multiples sollicitations qu’imposent les NTIC. L’utilisation massive des technologies pose en premier lieu un problème d’ergonomie. Il semble que nous ne soyons tout simplement pas faits pour regarder un écran d’ordinateur à 50 cm de notre nez douze heures par jour. Comme les neurologues l’ont montré, le multitâche provoque un effet euphorisant, une sensation de puissance qui nous donne l’illusion d’être hyperproductifs et nous entraîne à nous disperser toujours plus. Voilà pourquoi, quel que soit notre âge, nous tombons aussi vite amoureux des nouvelles technologies.</p>

	<p>Le technostress se manifeste également par une perte d’attention ou des difficultés de concentration. Habituées au multitâche, à la vitesse et à l’impression d’urgence permanente que donnent les NTIC, les personnes souffrant de technostress ne se sentent plus en phase avec la réalité. Il n’est pas rare que leur esprit vagabonde dans le flux de données, les conversations in vivo ne sont pas assez intenses pour elles. Leurs mains glissent irrémédiablement vers leurs téléphones afin de se « reconnecter » le plus rapidement possible en jouant, en envoyant des messages, en lisant des e-mails. Ces troubles de la concentration générés par les NTIC sont contre-productifs en entreprise et sont néfastes dans la vie privée.</p> 

	<p>De plus, une étude menée par des chercheurs de Microsoft montre que quand le travail d’un employé a été interrompu par une notification de réception d’un nouvel e-mail, il met environ 24 minutes pour retourner à la tâche interrompue. Quand vous répondez à une notification qui apparaît sur votre écran ou à la vibration de votre portable, vous prenez plus de temps que le seul temps nécessaire à la lecture du message. Vous devez également vous remettre de cette interruption et vous reconcentrer sur votre précédente tâche. Beaucoup de personnes utilisent cette interruption comme une opportunité permettant de consulter d’autres messages non lus ou pour effectuer des activités indépendantes comme envoyer un message à un ami ou pour surfer sur Internet. La charge de travail supplémentaire impose souvent au salarié de se coucher plus tard afin de boucler son travail. Le stress accumulé, l’excitation et l’urgence associés aux NTIC provoquent de nombreux troubles du sommeil.</p>

	<p>On pourrait penser que le technostress ne touche que les gros utilisateurs des NTIC mais chacun, quelle que soit son utilisation des NTIC, peut être touché par ce phénomène. Nous avons cru que nous allions pouvoir dominer le monde grâce à la technologie mais un simple écran bleu nous glace de frustration. L’incapacité de savoir ou de pouvoir utiliser la machine est une terrible frustration pour l’homme. Elle touche ceux qui n’arrivent pas à suivre le rythme éperdu des avancées technologiques et ceux qui s’y donnent entièrement sans y trouver la satisfaction escomptée lorsque la machine tombe en panne, par exemple. Pensez à la frustration que vous ressentez lorsque votre ordinateur est lent, quand un bug vous empêche de faire ce que vous souhaitiez ou lorsqu’un service technologique est indisponible. Nous sommes habitués à la haute disponibilité et à une réactivité éclair de nos machines, ainsi, la moindre défaillance plonge son utilisateur dans une situation de stress. Ce stress est augmenté par le fait que l’évolution des NTIC rend de plus en plus dépendants les hommes de leurs machines.</p>

	<p>Mis à part certains problèmes (troubles oculaires, tendinites etc.), la technologie a globalement tendance à favoriser la diminution de la pénibilité physique. En revanche, elle augmente la charge psychique ce qui se traduit par une probabilité accrue de risques psychosociaux et psychosomatiques. En effet, l’utilisation de la technologie exige une très grande activité mentale et cérébrale : haut degré de mémorisation, attention, vigilance, compréhension rapide de l’information, anticipation, acuité perceptive etc. Par ailleurs, plus la charge psychique augmente, plus les comportements du sujet au travail deviennent asociaux. Les risques sont alors le rejet, le repli, la fuite, la rétention d’information, l’agressivité, la violence, voire le suicide.</p>

<?php
include 'footer.php'; 
?>