<?php
include 'header.php'; 
?>
	<h1>II- Lutter contre le technostress</h1>
	<h2><a name="a"></a>A. Les actions possibles des entreprises</h2>
	<p>Le phénomène du technostress ayant été cerné dans la première partie, il est nécessaire de proposer des solutions afin d’endiguer ce problème.

	<p>L’entreprise doit jouer un rôle charnière dans la lutte contre le technostress : si chacun est libre d’utiliser comme il le souhaite les NTIC dans sa vie privée, l’entreprise impose le plus souvent aux salariés l’usage de ces outils. La mesure la plus facile et la plus rapide à mettre en place est l’élaboration d’une charte d’usage des NTIC. L’entreprise se doit de garantir l’interdiction d’utiliser certaines capacités de la technologie à d’autres buts que ceux affichés, par exemple la surveillance des salariés via la messagerie, des connexions internet ou de la géolocalisation. Si les changements des modes de management imposés par les NTIC sont inéluctables, cette évolution doit se faire progressivement. En effet, les modes de management s’exerceront désormais de plus en plus dans des modes en réseau, coopératifs, avec une approche différente du rôle de la hiérarchie.</p>

	<p>Si la forte utilisation des NTIC tend irrémédiablement à diminuer l’attention portée au destinataire, il est primordial de prendre en considération son interlocuteur. Ainsi, les salariés se doivent de respecter la vie privée de leurs collaborateurs en évitant les sollicitations hors temps de travail ou en s’interdisant de prendre connaissance et d’exploiter des informations de nature privée via la messagerie ou les réseaux sociaux. Concernant les e-mails, il convient d’identifier et de gérer les rôles de chacun lors des échanges en évitant les diffusions incontrôlées, les communications non structurées ou les allers retours sans fin non constructifs. Devant le flot d’e-mails que reçoivent les salariés, il est vital de leur enseigner la nécessité de répondre de manière précise et concise afin que le destinataire gagne du temps et qu’il comprenne l’objet du message sans ambiguïté. Dans la continuité, il est opportun de privilégier les échanges directs lorsque ceux-ci concernent des collaborateurs proches, des sujets sensibles ou méritant une forte dynamique d’échange.</p>

	<p>Ces recommandations de bons sens sont essentielles pour garantir une bonne utilisation des NTIC. L’entreprise doit proposer aux salariés un déploiement progressif et cohérent, soutenu par des actions de formation, d’accompagnement du changement et d’évaluation des nouveaux outils. Un dialogue doit être instauré avec le personnel pour favoriser l’appropriation par tous de ces nouveaux usages et un suivi qualité doit être effectué afin de déceler tout disfonctionnement.</p> 

	<p>Les entreprises se doivent de mener ces actions car elles sont les conditions initiatrices d’un usage adapté et dans de bonnes conditions des NTIC par les salariés. Quelques-unes ont pris conscience des enjeux : par exemple, Canon France a organisé une journée sans e-mails le 9 décembre 2010 afin de favoriser le bien-être de ses collaborateurs. Il est bien sur impossible d’interdire l’usage des e-mails dans les grandes entreprises mais de telles actions montrent bien que le problème est pris au sérieux et que les entreprises prennent des initiatives pour y remédier.</p>

	<p>Les mesures que doivent faire l’effort de prendre les entreprises ne suffisent pas, il incombe au salarié de prendre des initiatives de son propre chef afin d’éviter le technostress. Ceci peut commencer par la limitation de l’usage des NTIC : clarifier avec son entreprise que l’on souhaite pouvoir se déconnecter chez soi ou en vacances (d’autant plus que ces heures de télétravail ne sont généralement pas rémunérées), établir des règles de tri dans les e-mails permettant une meilleure gestion, accepter de ne pas pouvoir tout consulter et refuser la pression permanente imposée par la technologie.</p>
	
	<h2><a name="b"></a>B. La nécessité de la dimension humaine dans les relations interpersonnelles</h2>
	<p>Les NTIC doivent être à même de générer plus de liens, plus de sens et plus d’attention aux autres. L’utilisation de ces technologies est nécessaire mais elle doit garantir une part non négligeable à la dimension humaine des relations interpersonnelles au risque de tomber dans une totale déshumanisation des échanges.</p>

	<p>Les machines échangent des données entre elles tandis que l’homme accompagne l’information d’une charge émotionnelle. Quand deux collègues situés côte à côte s'échangent des e-mails plutôt que de se parler, ils ne communiquent plus. Comme nous l’avons abordé précédemment, il est bon de maintenir les relations interpersonnelles qui exigent une relation privilégiant le face à face ou les échanges en petits groupes comme les situations importantes ou particulières, les sanctions ou les reconnaissances, la remotivation d’une équipe. Le temps libéré par la productivité des relations numériques doit être réinvesti dans les relations face à face individuelles ou collectives (entretiens, réunions d’équipes…).</p> 

	<p>Quelques mesures simples de resocialisation consistent à interdire en réunion le smartphone, les tablettes, à respecter le droit à la déconnexion des salariés durant leurs temps de repos ou à imposer des rencontres physiques à des équipes habituellement gérées à distance. L’entreprise doit proposer aux salariés des lieux propices aux rencontres et aux échanges directs. Ainsi, elle doit veiller à l’existence et à l’animation de lieux et circonstances où puissent se ressourcer des relations face à face : réunions de lancements de projets, machines à café, pôles d’impression ou de photocopie, présentation des nouveaux arrivants, réunions de communautés...</p>

	<p>Il incombe à l’entreprise d’utiliser à bon escient les capacités offertes par les technologies numériques pour conserver chaque fois que possible une dimension humaine, spontanée et confiante.</p>
	<center><img src="//www.technostress.fr/images/pause-cafe-entreprise.jpg" width="500px" class="photo" alt="Une pause-café entre collaborateurs" /></center>
	<center><span class="italic">Une pause-café entre collaborateurs</span></center>
	<br />
	<h2><a name="c"></a>C. Prise de conscience des enjeux</h2>
	<p>Le technostress est un problème complexe, encore trop peu étudié et où les intérêts de chacun divergent.</p> 

	<p>Pour les entreprises, il représente un coût financier : il est considéré comme une forme de stress au travail qui représente chaque année entre 3 et 5 % du PIB. Au-delà de la dimension économique pure, la mauvaise utilisation des NTIC peut être responsable d’une baisse de la productivité (alors que c’est l’effet inverse qui est recherché), de la détérioration de la communication au sein de l’entreprise et du mal-être des salariés.</p>

	<p>Pour les salariés, l’enjeu est avant tout médical. Comme nous avons pu le constater, le technostress peut entrainer des troubles de l’attention, des troubles du sommeil, une situation extrême de surcharge (burn out), le repli sur soi, le rejet, la violence… Il est donc vital tant pour les entreprises que pour les salariés de comprendre les enjeux du technostress et de mettre en place les mesures qui s’imposent pour lutter contre celui-ci.</p>

	<p>Le stress psychosocial résulte de l’inadéquation entre le fonctionnement psychique, les besoins et les aspirations du salarié et l’organisation du travail. Nous avons besoin de temps morts, de phases absentes de sollicitations. De plus, l’anxiété et la dépression émergent davantage au fur et à mesure que les individus se doivent d’assimiler des données sans cesse nouvelles. Il faut donc travailler à la gestion de la quantité d’information : savoir par exemple distinguer l’important de l’urgent.</p>

	<p>Mais comme souvent, ce n'est pas tant la technologie qui doit être mise en cause mais bien l'usage que nous en faisons. Les smartphones, les ordinateurs, l’Internet sont devenus des composantes essentielles de l'organisation de notre vie familiale, sociale et professionnelle. Apprenons donc à les utiliser, au-delà de la simple notice technique. Soyons conscients de la charge qu'ils font peser sur nos capacités attentionnelles et du stress que ces technologies peuvent créer. Les développements récents des neurosciences cognitives permettent maintenant d'envisager de véritables programmes d'éducation de l'attention, renseignant sur ses limites et son bon usage. </p>

	<p>Dans cet univers de multitâche permanent, ce bon usage ne va plus de soi et il est peut-être temps d'envisager une véritable éducation de l'attention, notamment en milieu scolaire, qui prépare dès l'enfance à la vie connectée. Les digital natives (les personnes ayant grandi dans un environnement numérique) présentent un manque d’empathie à force d’échanger sous forme écrite via les nouvelles technologies. Face à ce constat, il serait opportun de créer des modules de sensibilisation à l’usage de ces technologies au cours du secondaire ou du supérieur, d’informer la population des risques liés à l’utilisation des NTIC ce qui permettrait une intégration saine de ces outils dans notre vie.</p>

<?php
include 'footer.php'; 
?>